global:
  nameOverride: ""
  fullnameOverride: ""

  app:
    release: "not_set"
    version: "not_set"
    project: "not_set"
    customer: "shared"
    environment: "dev"

  replicaCount: 2

  image:
    name: changeme
    tag: changeme
    pullPolicy: Always

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi
      ephemeral-storage: 1Gi

  env:
    JAVA_TOOL_OPTIONS: -XX:+PrintCommandLineFlags -XX:InitialRAMPercentage=80 -XX:MaxRAMPercentage=80

  secrets: {}

  configMaps: {}

  volumeMounts: {}

  volumes: {}

  imagePullSecrets: {}

  serviceAccount:
    name: ""

  podSecurityContext:
    runAsUser: 10001
    runAsGroup: 30001
    fsGroup: 20001

  podAnnotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "false"

  securityContext:
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

  service:
    type: ClusterIP
    ports:
      - port: 8080
        name: http
        # routing is optional and only used when istio gateway is enabled
        # ACHTUNG: if port has no routing configuration then it will be exposed only internally
        routing:
          # retries is optional
          retries:
            attempts: 3
            perTryTimeout: 2s
            retryOn: 5xx
        # corsPolicy:
        #  allowMethods:
        #    - "*"
        #  allowHeaders:
        #    - "*"
        #  maxAge: "24h"

  healthProbe:
    port: 8080
    initialDelaySeconds: 15
    liveness: /health/liveness
    readiness: /health/readiness

  istio:
    gateway:
      enabled: false
      name: changeme-public-gateway
      host: changeme.dev.pej.se
      credentialName: changeme-cert
      clusterIssuer: letsencrypt-prod
      auth:
        enabled: false
        provider: ext-authz

  prometheus:
    enabled: true
    port: 8080
    path: /metrics

  cloudSqlProxy:
    enabled: false
    instance: <project>:<location>:<db>
    tag: 2.13.0
    resources:
      requests:
        memory: 128Mi
        cpu: 10m
      limits:
        memory: 256Mi
        cpu: 250m

  extraContainers: {}
