global:
  nameOverride: ""
  fullnameOverride: ""

  replicaCount: 2

  image:
    name: changeme
    tag: changeme
    pullPolicy: Always

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi
      ephemeral-storage: 1Gi

  env:
    JAVA_TOOL_OPTIONS: -XX:+PrintCommandLineFlags -XX:InitialRAMPercentage=80 -XX:MaxRAMPercentage=80

  secrets: {}

  imagePullSecrets:
    - name: image-pull-secrets

  serviceAccount:
    name: ""

  podSecurityContext:
    runAsUser: 10001
    runAsGroup: 30001
    fsGroup: 20001

  podAnnotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "false"

  securityContext:
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

  service:
    type: ClusterIP
    ports:
      - port: 9090
        name: grpc
        # routing is optional and only used when istio gateway is enabled
        # ACHTUNG: if port has no routing configuration then it will be exposed only internally
        routing:
          # match is optional, if it is ommitted then all requests will be matched
          match:
            - uri:
                prefix: "/pej."
            - uri:
                prefix: "/grpc."
          # retries is optional
          retries:
            attempts: 3
            perTryTimeout: 2s
            retryOn: cancelled,deadline-exceeded,internal,unavailable
# example http config:
#      - port: 8080
#        name: http
#        routing:
#          retries:
#            attempts: 3
#            perTryTimeout: 2s
#            retryOn: 5xx

  healthProbe:
    port: 8080
    initialDelaySeconds: 15
    liveness: /actuator/health/liveness
    readiness: /actuator/health/readiness

  istio:
    gateway:
      enabled: false
      name: changeme-public-gateway
      host: changeme.dev.pej.se
      credentialName: changeme-cert
      clusterIssuer: letsencrypt-prod

  prometheus:
    enabled: true
    port: 8080
    path: /actuator/prometheus

  cloudSqlProxy:
    enabled: false
    instances: <project>:<location>:<db>=tcp:<port>
    tag: 1.28.0
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 150m

  extraContainers: {}
