{{- if .Values.global.istio.gateway.auth.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.pejLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  action: CUSTOM
  provider:
    name: {{ .Values.global.istio.gateway.auth.provider }}
  rules:
    - to:
      - operation:
          hosts: ["{{ .Values.global.istio.gateway.host }}"]
    - to:
      - operation:
          paths: ["/pej.*", "/grpc.*"]
{{- end }}
