apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    {{- include "app.pejAnnotations" . | nindent 4 }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.service.type }}
  ports:
    {{- range .Values.global.service.ports }}
    - port: {{ .port }}
      name: {{ .name }}
      {{- if .targetPort}}
      targetPort: {{.targetPort}}
      {{- end}}
    {{- end }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
