{{- if .Values.global.istio.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ include "app.name" . }}
spec:
  hosts:
    - {{ .Values.global.istio.gateway.host }}
  gateways:
    - {{ .Values.global.istio.gateway.name }}
  http:
    {{- $host := include "app.name" . }}
    {{- range .Values.global.service.ports }}
    {{- if .routing }}
    - route:
        - destination:
            host: {{ $host }}
            port:
              number: {{ .port }}
      {{- with ((.routing).match) }}
      match:
        {{- toYaml .| nindent 8 }}
      {{- end }}
      {{- with ((.routing).rewrite) }}
      rewrite:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with ((.routing).retries) }}
      retries:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{-  with ((.routing).corsPolicy) }}
      corsPolicy:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
