name: Release Charts

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - uses: azure/setup-helm@v1
        with:
          version: v3.16.4
      - uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: bsord/helm-push@4.2.0
        with:
          useOCIRegistry: true
          registry-url: ${{ secrets.OCI_URL }}
          username: ${{ secrets.OCI_USERNAME }}
          access-token: ${{ secrets.OCI_TOKEN }}
          chart-folder: charts
